<?xml version="1.0" encoding="utf-8"?><Database Name="renatadb" Class="renataDBMLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=NEBULUS_PC\SQLEXPRESS;Initial Catalog=renatadb;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="renatadbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Newsletter" Member="Newsletters">
    <Type Name="Newsletter">
      <Column Name="IdListaEmail" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IP" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Endereco" Member="Enderecos">
    <Type Name="Endereco">
      <Column Name="IdEndereco" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Endereco" Member="Endereco1" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Complemento" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Bairro" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Cidade" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CEP" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Noticia" Member="Noticias">
    <Type Name="Noticia">
      <Column Name="IdNoticia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Titulo" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="DescricaoBreve" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Conteudo" Type="System.String" DbType="VarChar(1500)" CanBeNull="true" />
      <Column Name="DataPublicacao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CaminhoImagem" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuario" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Senha" Type="System.Data.Linq.Binary" DbType="Binary(20) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CPF" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="fkEndereco" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Servico" Member="Servicos">
    <Type Name="Servico">
      <Column Name="IdServicos" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Descricao" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Valor" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CaminhoImagem" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Log]" Member="Logs">
    <Type Name="Log">
      <Column Name="IdLog" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mensagem" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="DataHora" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>