#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_RENATA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="renataDB")]
	public partial class RR_DALDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAtendimento(Atendimento instance);
    partial void UpdateAtendimento(Atendimento instance);
    partial void DeleteAtendimento(Atendimento instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertCarrinhoCompra(CarrinhoCompra instance);
    partial void UpdateCarrinhoCompra(CarrinhoCompra instance);
    partial void DeleteCarrinhoCompra(CarrinhoCompra instance);
    partial void InsertDetalheCompra(DetalheCompra instance);
    partial void UpdateDetalheCompra(DetalheCompra instance);
    partial void DeleteDetalheCompra(DetalheCompra instance);
    partial void InsertEndereco(Endereco instance);
    partial void UpdateEndereco(Endereco instance);
    partial void DeleteEndereco(Endereco instance);
    partial void InsertImagens(Imagens instance);
    partial void UpdateImagens(Imagens instance);
    partial void DeleteImagens(Imagens instance);
    partial void InsertNewsletter(Newsletter instance);
    partial void UpdateNewsletter(Newsletter instance);
    partial void DeleteNewsletter(Newsletter instance);
    partial void InsertNoticia(Noticia instance);
    partial void UpdateNoticia(Noticia instance);
    partial void DeleteNoticia(Noticia instance);
    partial void InsertProduto(Produto instance);
    partial void UpdateProduto(Produto instance);
    partial void DeleteProduto(Produto instance);
    partial void InsertServico(Servico instance);
    partial void UpdateServico(Servico instance);
    partial void DeleteServico(Servico instance);
    #endregion
		
		public RR_DALDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["renataDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RR_DALDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RR_DALDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RR_DALDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RR_DALDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Atendimento> Atendimentos
		{
			get
			{
				return this.GetTable<Atendimento>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<CarrinhoCompra> CarrinhoCompras
		{
			get
			{
				return this.GetTable<CarrinhoCompra>();
			}
		}
		
		public System.Data.Linq.Table<DetalheCompra> DetalheCompras
		{
			get
			{
				return this.GetTable<DetalheCompra>();
			}
		}
		
		public System.Data.Linq.Table<Endereco> Enderecos
		{
			get
			{
				return this.GetTable<Endereco>();
			}
		}
		
		public System.Data.Linq.Table<Imagens> Imagens
		{
			get
			{
				return this.GetTable<Imagens>();
			}
		}
		
		public System.Data.Linq.Table<Newsletter> Newsletters
		{
			get
			{
				return this.GetTable<Newsletter>();
			}
		}
		
		public System.Data.Linq.Table<Noticia> Noticias
		{
			get
			{
				return this.GetTable<Noticia>();
			}
		}
		
		public System.Data.Linq.Table<Produto> Produtos
		{
			get
			{
				return this.GetTable<Produto>();
			}
		}
		
		public System.Data.Linq.Table<Servico> Servicos
		{
			get
			{
				return this.GetTable<Servico>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Atendimento")]
	public partial class Atendimento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdAtenidmento;
		
		private System.Nullable<System.DateTime> _Data;
		
		private System.Nullable<int> _IdServico;
		
		private System.Nullable<int> _IdUsuario;
		
		private EntityRef<Usuario> _Usuario;
		
		private EntityRef<Servico> _Servico;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAtenidmentoChanging(int value);
    partial void OnIdAtenidmentoChanged();
    partial void OnDataChanging(System.Nullable<System.DateTime> value);
    partial void OnDataChanged();
    partial void OnIdServicoChanging(System.Nullable<int> value);
    partial void OnIdServicoChanged();
    partial void OnIdUsuarioChanging(System.Nullable<int> value);
    partial void OnIdUsuarioChanged();
    #endregion
		
		public Atendimento()
		{
			this._Usuario = default(EntityRef<Usuario>);
			this._Servico = default(EntityRef<Servico>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAtenidmento", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdAtenidmento
		{
			get
			{
				return this._IdAtenidmento;
			}
			set
			{
				if ((this._IdAtenidmento != value))
				{
					this.OnIdAtenidmentoChanging(value);
					this.SendPropertyChanging();
					this._IdAtenidmento = value;
					this.SendPropertyChanged("IdAtenidmento");
					this.OnIdAtenidmentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="DateTime")]
		public System.Nullable<System.DateTime> Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdServico", DbType="Int")]
		public System.Nullable<int> IdServico
		{
			get
			{
				return this._IdServico;
			}
			set
			{
				if ((this._IdServico != value))
				{
					if (this._Servico.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdServicoChanging(value);
					this.SendPropertyChanging();
					this._IdServico = value;
					this.SendPropertyChanged("IdServico");
					this.OnIdServicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int")]
		public System.Nullable<int> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Atendimento", Storage="_Usuario", ThisKey="IdUsuario", OtherKey="idUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Atendimentos.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Atendimentos.Add(this);
						this._IdUsuario = value.idUsuario;
					}
					else
					{
						this._IdUsuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Servico_Atendimento", Storage="_Servico", ThisKey="IdServico", OtherKey="IdServico", IsForeignKey=true)]
		public Servico Servico
		{
			get
			{
				return this._Servico.Entity;
			}
			set
			{
				Servico previousValue = this._Servico.Entity;
				if (((previousValue != value) 
							|| (this._Servico.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Servico.Entity = null;
						previousValue.Atendimentos.Remove(this);
					}
					this._Servico.Entity = value;
					if ((value != null))
					{
						value.Atendimentos.Add(this);
						this._IdServico = value.IdServico;
					}
					else
					{
						this._IdServico = default(Nullable<int>);
					}
					this.SendPropertyChanged("Servico");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idUsuario;
		
		private System.Nullable<int> _TipoUsuario;
		
		private string _Nome;
		
		private string _CPF;
		
		private string _Endereço;
		
		private string _Telefone;
		
		private string _Email;
		
		private string _Senha;
		
		private string _DataNascimento;
		
		private EntitySet<Atendimento> _Atendimentos;
		
		private EntitySet<CarrinhoCompra> _CarrinhoCompras;
		
		private EntitySet<Endereco> _Enderecos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    partial void OnTipoUsuarioChanging(System.Nullable<int> value);
    partial void OnTipoUsuarioChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCPFChanging(string value);
    partial void OnCPFChanged();
    partial void OnEndereçoChanging(string value);
    partial void OnEndereçoChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSenhaChanging(string value);
    partial void OnSenhaChanged();
    partial void OnDataNascimentoChanging(string value);
    partial void OnDataNascimentoChanged();
    #endregion
		
		public Usuario()
		{
			this._Atendimentos = new EntitySet<Atendimento>(new Action<Atendimento>(this.attach_Atendimentos), new Action<Atendimento>(this.detach_Atendimentos));
			this._CarrinhoCompras = new EntitySet<CarrinhoCompra>(new Action<CarrinhoCompra>(this.attach_CarrinhoCompras), new Action<CarrinhoCompra>(this.detach_CarrinhoCompras));
			this._Enderecos = new EntitySet<Endereco>(new Action<Endereco>(this.attach_Enderecos), new Action<Endereco>(this.detach_Enderecos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoUsuario", DbType="Int")]
		public System.Nullable<int> TipoUsuario
		{
			get
			{
				return this._TipoUsuario;
			}
			set
			{
				if ((this._TipoUsuario != value))
				{
					this.OnTipoUsuarioChanging(value);
					this.SendPropertyChanging();
					this._TipoUsuario = value;
					this.SendPropertyChanged("TipoUsuario");
					this.OnTipoUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(100)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="VarChar(50)")]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this.OnCPFChanging(value);
					this.SendPropertyChanging();
					this._CPF = value;
					this.SendPropertyChanged("CPF");
					this.OnCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endereço", DbType="VarChar(100)")]
		public string Endereço
		{
			get
			{
				return this._Endereço;
			}
			set
			{
				if ((this._Endereço != value))
				{
					this.OnEndereçoChanging(value);
					this.SendPropertyChanging();
					this._Endereço = value;
					this.SendPropertyChanged("Endereço");
					this.OnEndereçoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="NChar(10)")]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Senha", DbType="VarChar(50)")]
		public string Senha
		{
			get
			{
				return this._Senha;
			}
			set
			{
				if ((this._Senha != value))
				{
					this.OnSenhaChanging(value);
					this.SendPropertyChanging();
					this._Senha = value;
					this.SendPropertyChanged("Senha");
					this.OnSenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNascimento", DbType="VarChar(50)")]
		public string DataNascimento
		{
			get
			{
				return this._DataNascimento;
			}
			set
			{
				if ((this._DataNascimento != value))
				{
					this.OnDataNascimentoChanging(value);
					this.SendPropertyChanging();
					this._DataNascimento = value;
					this.SendPropertyChanged("DataNascimento");
					this.OnDataNascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Atendimento", Storage="_Atendimentos", ThisKey="idUsuario", OtherKey="IdUsuario")]
		public EntitySet<Atendimento> Atendimentos
		{
			get
			{
				return this._Atendimentos;
			}
			set
			{
				this._Atendimentos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_CarrinhoCompra", Storage="_CarrinhoCompras", ThisKey="idUsuario", OtherKey="IdUsuario")]
		public EntitySet<CarrinhoCompra> CarrinhoCompras
		{
			get
			{
				return this._CarrinhoCompras;
			}
			set
			{
				this._CarrinhoCompras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Endereco", Storage="_Enderecos", ThisKey="idUsuario", OtherKey="IdUsuario")]
		public EntitySet<Endereco> Enderecos
		{
			get
			{
				return this._Enderecos;
			}
			set
			{
				this._Enderecos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Atendimentos(Atendimento entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Atendimentos(Atendimento entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_CarrinhoCompras(CarrinhoCompra entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_CarrinhoCompras(CarrinhoCompra entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Enderecos(Endereco entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Enderecos(Endereco entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CarrinhoCompra")]
	public partial class CarrinhoCompra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCarrinho;
		
		private System.Nullable<int> _IdDetalheCompra;
		
		private System.Nullable<System.DateTime> _Data;
		
		private System.Nullable<decimal> _Total;
		
		private System.Nullable<int> _IdUsuario;
		
		private EntityRef<Usuario> _Usuario;
		
		private EntityRef<DetalheCompra> _DetalheCompra;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCarrinhoChanging(int value);
    partial void OnIdCarrinhoChanged();
    partial void OnIdDetalheCompraChanging(System.Nullable<int> value);
    partial void OnIdDetalheCompraChanged();
    partial void OnDataChanging(System.Nullable<System.DateTime> value);
    partial void OnDataChanged();
    partial void OnTotalChanging(System.Nullable<decimal> value);
    partial void OnTotalChanged();
    partial void OnIdUsuarioChanging(System.Nullable<int> value);
    partial void OnIdUsuarioChanged();
    #endregion
		
		public CarrinhoCompra()
		{
			this._Usuario = default(EntityRef<Usuario>);
			this._DetalheCompra = default(EntityRef<DetalheCompra>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCarrinho", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdCarrinho
		{
			get
			{
				return this._IdCarrinho;
			}
			set
			{
				if ((this._IdCarrinho != value))
				{
					this.OnIdCarrinhoChanging(value);
					this.SendPropertyChanging();
					this._IdCarrinho = value;
					this.SendPropertyChanged("IdCarrinho");
					this.OnIdCarrinhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDetalheCompra", DbType="Int")]
		public System.Nullable<int> IdDetalheCompra
		{
			get
			{
				return this._IdDetalheCompra;
			}
			set
			{
				if ((this._IdDetalheCompra != value))
				{
					if (this._DetalheCompra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdDetalheCompraChanging(value);
					this.SendPropertyChanging();
					this._IdDetalheCompra = value;
					this.SendPropertyChanged("IdDetalheCompra");
					this.OnIdDetalheCompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="DateTime")]
		public System.Nullable<System.DateTime> Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Money")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int")]
		public System.Nullable<int> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_CarrinhoCompra", Storage="_Usuario", ThisKey="IdUsuario", OtherKey="idUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.CarrinhoCompras.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.CarrinhoCompras.Add(this);
						this._IdUsuario = value.idUsuario;
					}
					else
					{
						this._IdUsuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DetalheCompra_CarrinhoCompra", Storage="_DetalheCompra", ThisKey="IdDetalheCompra", OtherKey="IdDetalheCompra", IsForeignKey=true)]
		public DetalheCompra DetalheCompra
		{
			get
			{
				return this._DetalheCompra.Entity;
			}
			set
			{
				DetalheCompra previousValue = this._DetalheCompra.Entity;
				if (((previousValue != value) 
							|| (this._DetalheCompra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DetalheCompra.Entity = null;
						previousValue.CarrinhoCompras.Remove(this);
					}
					this._DetalheCompra.Entity = value;
					if ((value != null))
					{
						value.CarrinhoCompras.Add(this);
						this._IdDetalheCompra = value.IdDetalheCompra;
					}
					else
					{
						this._IdDetalheCompra = default(Nullable<int>);
					}
					this.SendPropertyChanged("DetalheCompra");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DetalheCompra")]
	public partial class DetalheCompra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdDetalheCompra;
		
		private System.Nullable<int> _Quantidade;
		
		private System.Nullable<int> _IdProduto;
		
		private System.Nullable<decimal> _Subtotal;
		
		private EntitySet<CarrinhoCompra> _CarrinhoCompras;
		
		private EntityRef<Produto> _Produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDetalheCompraChanging(int value);
    partial void OnIdDetalheCompraChanged();
    partial void OnQuantidadeChanging(System.Nullable<int> value);
    partial void OnQuantidadeChanged();
    partial void OnIdProdutoChanging(System.Nullable<int> value);
    partial void OnIdProdutoChanged();
    partial void OnSubtotalChanging(System.Nullable<decimal> value);
    partial void OnSubtotalChanged();
    #endregion
		
		public DetalheCompra()
		{
			this._CarrinhoCompras = new EntitySet<CarrinhoCompra>(new Action<CarrinhoCompra>(this.attach_CarrinhoCompras), new Action<CarrinhoCompra>(this.detach_CarrinhoCompras));
			this._Produto = default(EntityRef<Produto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDetalheCompra", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdDetalheCompra
		{
			get
			{
				return this._IdDetalheCompra;
			}
			set
			{
				if ((this._IdDetalheCompra != value))
				{
					this.OnIdDetalheCompraChanging(value);
					this.SendPropertyChanging();
					this._IdDetalheCompra = value;
					this.SendPropertyChanged("IdDetalheCompra");
					this.OnIdDetalheCompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantidade", DbType="Int")]
		public System.Nullable<int> Quantidade
		{
			get
			{
				return this._Quantidade;
			}
			set
			{
				if ((this._Quantidade != value))
				{
					this.OnQuantidadeChanging(value);
					this.SendPropertyChanging();
					this._Quantidade = value;
					this.SendPropertyChanged("Quantidade");
					this.OnQuantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProduto", DbType="Int")]
		public System.Nullable<int> IdProduto
		{
			get
			{
				return this._IdProduto;
			}
			set
			{
				if ((this._IdProduto != value))
				{
					if (this._Produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdProdutoChanging(value);
					this.SendPropertyChanging();
					this._IdProduto = value;
					this.SendPropertyChanged("IdProduto");
					this.OnIdProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subtotal", DbType="Money")]
		public System.Nullable<decimal> Subtotal
		{
			get
			{
				return this._Subtotal;
			}
			set
			{
				if ((this._Subtotal != value))
				{
					this.OnSubtotalChanging(value);
					this.SendPropertyChanging();
					this._Subtotal = value;
					this.SendPropertyChanged("Subtotal");
					this.OnSubtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DetalheCompra_CarrinhoCompra", Storage="_CarrinhoCompras", ThisKey="IdDetalheCompra", OtherKey="IdDetalheCompra")]
		public EntitySet<CarrinhoCompra> CarrinhoCompras
		{
			get
			{
				return this._CarrinhoCompras;
			}
			set
			{
				this._CarrinhoCompras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_DetalheCompra", Storage="_Produto", ThisKey="IdProduto", OtherKey="IdProduto", IsForeignKey=true)]
		public Produto Produto
		{
			get
			{
				return this._Produto.Entity;
			}
			set
			{
				Produto previousValue = this._Produto.Entity;
				if (((previousValue != value) 
							|| (this._Produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produto.Entity = null;
						previousValue.DetalheCompras.Remove(this);
					}
					this._Produto.Entity = value;
					if ((value != null))
					{
						value.DetalheCompras.Add(this);
						this._IdProduto = value.IdProduto;
					}
					else
					{
						this._IdProduto = default(Nullable<int>);
					}
					this.SendPropertyChanged("Produto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CarrinhoCompras(CarrinhoCompra entity)
		{
			this.SendPropertyChanging();
			entity.DetalheCompra = this;
		}
		
		private void detach_CarrinhoCompras(CarrinhoCompra entity)
		{
			this.SendPropertyChanging();
			entity.DetalheCompra = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Endereco")]
	public partial class Endereco : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEndereco;
		
		private string _Endereco1;
		
		private string _Complemento;
		
		private string _Bairro;
		
		private string _Cidade;
		
		private string _Estado;
		
		private string _CEP;
		
		private System.Nullable<int> _IdUsuario;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEnderecoChanging(int value);
    partial void OnIdEnderecoChanged();
    partial void OnEndereco1Changing(string value);
    partial void OnEndereco1Changed();
    partial void OnComplementoChanging(string value);
    partial void OnComplementoChanged();
    partial void OnBairroChanging(string value);
    partial void OnBairroChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnCEPChanging(string value);
    partial void OnCEPChanged();
    partial void OnIdUsuarioChanging(System.Nullable<int> value);
    partial void OnIdUsuarioChanged();
    #endregion
		
		public Endereco()
		{
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEndereco", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdEndereco
		{
			get
			{
				return this._IdEndereco;
			}
			set
			{
				if ((this._IdEndereco != value))
				{
					this.OnIdEnderecoChanging(value);
					this.SendPropertyChanging();
					this._IdEndereco = value;
					this.SendPropertyChanged("IdEndereco");
					this.OnIdEnderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Endereco", Storage="_Endereco1", DbType="VarChar(100)")]
		public string Endereco1
		{
			get
			{
				return this._Endereco1;
			}
			set
			{
				if ((this._Endereco1 != value))
				{
					this.OnEndereco1Changing(value);
					this.SendPropertyChanging();
					this._Endereco1 = value;
					this.SendPropertyChanged("Endereco1");
					this.OnEndereco1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Complemento", DbType="VarChar(100)")]
		public string Complemento
		{
			get
			{
				return this._Complemento;
			}
			set
			{
				if ((this._Complemento != value))
				{
					this.OnComplementoChanging(value);
					this.SendPropertyChanging();
					this._Complemento = value;
					this.SendPropertyChanged("Complemento");
					this.OnComplementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bairro", DbType="VarChar(100)")]
		public string Bairro
		{
			get
			{
				return this._Bairro;
			}
			set
			{
				if ((this._Bairro != value))
				{
					this.OnBairroChanging(value);
					this.SendPropertyChanging();
					this._Bairro = value;
					this.SendPropertyChanged("Bairro");
					this.OnBairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="VarChar(100)")]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(100)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="VarChar(100)")]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int")]
		public System.Nullable<int> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Endereco", Storage="_Usuario", ThisKey="IdUsuario", OtherKey="idUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Enderecos.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Enderecos.Add(this);
						this._IdUsuario = value.idUsuario;
					}
					else
					{
						this._IdUsuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Imagens")]
	public partial class Imagens : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdImagens;
		
		private string _Titulo;
		
		private string _CaminhoImagem;
		
		private System.Nullable<int> _IdProduto;
		
		private EntityRef<Produto> _Produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdImagensChanging(int value);
    partial void OnIdImagensChanged();
    partial void OnTituloChanging(string value);
    partial void OnTituloChanged();
    partial void OnCaminhoImagemChanging(string value);
    partial void OnCaminhoImagemChanged();
    partial void OnIdProdutoChanging(System.Nullable<int> value);
    partial void OnIdProdutoChanged();
    #endregion
		
		public Imagens()
		{
			this._Produto = default(EntityRef<Produto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImagens", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdImagens
		{
			get
			{
				return this._IdImagens;
			}
			set
			{
				if ((this._IdImagens != value))
				{
					this.OnIdImagensChanging(value);
					this.SendPropertyChanging();
					this._IdImagens = value;
					this.SendPropertyChanged("IdImagens");
					this.OnIdImagensChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(80)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this.OnTituloChanging(value);
					this.SendPropertyChanging();
					this._Titulo = value;
					this.SendPropertyChanged("Titulo");
					this.OnTituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaminhoImagem", DbType="VarChar(1000)")]
		public string CaminhoImagem
		{
			get
			{
				return this._CaminhoImagem;
			}
			set
			{
				if ((this._CaminhoImagem != value))
				{
					this.OnCaminhoImagemChanging(value);
					this.SendPropertyChanging();
					this._CaminhoImagem = value;
					this.SendPropertyChanged("CaminhoImagem");
					this.OnCaminhoImagemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProduto", DbType="Int")]
		public System.Nullable<int> IdProduto
		{
			get
			{
				return this._IdProduto;
			}
			set
			{
				if ((this._IdProduto != value))
				{
					if (this._Produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdProdutoChanging(value);
					this.SendPropertyChanging();
					this._IdProduto = value;
					this.SendPropertyChanged("IdProduto");
					this.OnIdProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_Imagens", Storage="_Produto", ThisKey="IdProduto", OtherKey="IdProduto", IsForeignKey=true)]
		public Produto Produto
		{
			get
			{
				return this._Produto.Entity;
			}
			set
			{
				Produto previousValue = this._Produto.Entity;
				if (((previousValue != value) 
							|| (this._Produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produto.Entity = null;
						previousValue.Imagens.Remove(this);
					}
					this._Produto.Entity = value;
					if ((value != null))
					{
						value.Imagens.Add(this);
						this._IdProduto = value.IdProduto;
					}
					else
					{
						this._IdProduto = default(Nullable<int>);
					}
					this.SendPropertyChanged("Produto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ListaEmail")]
	public partial class Newsletter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdListaEmail;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _Data;
		
		private string _IP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdListaEmailChanging(int value);
    partial void OnIdListaEmailChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDataChanging(System.Nullable<System.DateTime> value);
    partial void OnDataChanged();
    partial void OnIPChanging(string value);
    partial void OnIPChanged();
    #endregion
		
		public Newsletter()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdListaEmail", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdListaEmail
		{
			get
			{
				return this._IdListaEmail;
			}
			set
			{
				if ((this._IdListaEmail != value))
				{
					this.OnIdListaEmailChanging(value);
					this.SendPropertyChanging();
					this._IdListaEmail = value;
					this.SendPropertyChanged("IdListaEmail");
					this.OnIdListaEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="DateTime")]
		public System.Nullable<System.DateTime> Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP", DbType="VarChar(30)")]
		public string IP
		{
			get
			{
				return this._IP;
			}
			set
			{
				if ((this._IP != value))
				{
					this.OnIPChanging(value);
					this.SendPropertyChanging();
					this._IP = value;
					this.SendPropertyChanged("IP");
					this.OnIPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Noticia")]
	public partial class Noticia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdNoticia;
		
		private string _Titulo;
		
		private string _DescricaoBreve;
		
		private string _Noticia1;
		
		private System.Nullable<System.DateTime> _DataPublicacao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdNoticiaChanging(int value);
    partial void OnIdNoticiaChanged();
    partial void OnTituloChanging(string value);
    partial void OnTituloChanged();
    partial void OnDescricaoBreveChanging(string value);
    partial void OnDescricaoBreveChanged();
    partial void OnNoticia1Changing(string value);
    partial void OnNoticia1Changed();
    partial void OnDataPublicacaoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataPublicacaoChanged();
    #endregion
		
		public Noticia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNoticia", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdNoticia
		{
			get
			{
				return this._IdNoticia;
			}
			set
			{
				if ((this._IdNoticia != value))
				{
					this.OnIdNoticiaChanging(value);
					this.SendPropertyChanging();
					this._IdNoticia = value;
					this.SendPropertyChanged("IdNoticia");
					this.OnIdNoticiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(80)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this.OnTituloChanging(value);
					this.SendPropertyChanging();
					this._Titulo = value;
					this.SendPropertyChanged("Titulo");
					this.OnTituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescricaoBreve", DbType="VarChar(100)")]
		public string DescricaoBreve
		{
			get
			{
				return this._DescricaoBreve;
			}
			set
			{
				if ((this._DescricaoBreve != value))
				{
					this.OnDescricaoBreveChanging(value);
					this.SendPropertyChanging();
					this._DescricaoBreve = value;
					this.SendPropertyChanged("DescricaoBreve");
					this.OnDescricaoBreveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Noticia", Storage="_Noticia1", DbType="VarChar(1500)")]
		public string Noticia1
		{
			get
			{
				return this._Noticia1;
			}
			set
			{
				if ((this._Noticia1 != value))
				{
					this.OnNoticia1Changing(value);
					this.SendPropertyChanging();
					this._Noticia1 = value;
					this.SendPropertyChanged("Noticia1");
					this.OnNoticia1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataPublicacao", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataPublicacao
		{
			get
			{
				return this._DataPublicacao;
			}
			set
			{
				if ((this._DataPublicacao != value))
				{
					this.OnDataPublicacaoChanging(value);
					this.SendPropertyChanging();
					this._DataPublicacao = value;
					this.SendPropertyChanged("DataPublicacao");
					this.OnDataPublicacaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produto")]
	public partial class Produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdProduto;
		
		private string _Nome;
		
		private string _Descricao;
		
		private System.Nullable<decimal> _Preco;
		
		private System.Nullable<int> _Estoque;
		
		private EntitySet<DetalheCompra> _DetalheCompras;
		
		private EntitySet<Imagens> _Imagens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdProdutoChanging(int value);
    partial void OnIdProdutoChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    partial void OnPrecoChanging(System.Nullable<decimal> value);
    partial void OnPrecoChanged();
    partial void OnEstoqueChanging(System.Nullable<int> value);
    partial void OnEstoqueChanged();
    #endregion
		
		public Produto()
		{
			this._DetalheCompras = new EntitySet<DetalheCompra>(new Action<DetalheCompra>(this.attach_DetalheCompras), new Action<DetalheCompra>(this.detach_DetalheCompras));
			this._Imagens = new EntitySet<Imagens>(new Action<Imagens>(this.attach_Imagens), new Action<Imagens>(this.detach_Imagens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProduto", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdProduto
		{
			get
			{
				return this._IdProduto;
			}
			set
			{
				if ((this._IdProduto != value))
				{
					this.OnIdProdutoChanging(value);
					this.SendPropertyChanging();
					this._IdProduto = value;
					this.SendPropertyChanged("IdProduto");
					this.OnIdProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(100)")]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Preco", DbType="Money")]
		public System.Nullable<decimal> Preco
		{
			get
			{
				return this._Preco;
			}
			set
			{
				if ((this._Preco != value))
				{
					this.OnPrecoChanging(value);
					this.SendPropertyChanging();
					this._Preco = value;
					this.SendPropertyChanged("Preco");
					this.OnPrecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estoque", DbType="Int")]
		public System.Nullable<int> Estoque
		{
			get
			{
				return this._Estoque;
			}
			set
			{
				if ((this._Estoque != value))
				{
					this.OnEstoqueChanging(value);
					this.SendPropertyChanging();
					this._Estoque = value;
					this.SendPropertyChanged("Estoque");
					this.OnEstoqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_DetalheCompra", Storage="_DetalheCompras", ThisKey="IdProduto", OtherKey="IdProduto")]
		public EntitySet<DetalheCompra> DetalheCompras
		{
			get
			{
				return this._DetalheCompras;
			}
			set
			{
				this._DetalheCompras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_Imagens", Storage="_Imagens", ThisKey="IdProduto", OtherKey="IdProduto")]
		public EntitySet<Imagens> Imagens
		{
			get
			{
				return this._Imagens;
			}
			set
			{
				this._Imagens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetalheCompras(DetalheCompra entity)
		{
			this.SendPropertyChanging();
			entity.Produto = this;
		}
		
		private void detach_DetalheCompras(DetalheCompra entity)
		{
			this.SendPropertyChanging();
			entity.Produto = null;
		}
		
		private void attach_Imagens(Imagens entity)
		{
			this.SendPropertyChanging();
			entity.Produto = this;
		}
		
		private void detach_Imagens(Imagens entity)
		{
			this.SendPropertyChanging();
			entity.Produto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Servico")]
	public partial class Servico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdServico;
		
		private string _Nome;
		
		private string _Descricao;
		
		private System.Nullable<decimal> _Valor;
		
		private string _CaminhoImagem;
		
		private EntitySet<Atendimento> _Atendimentos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdServicoChanging(int value);
    partial void OnIdServicoChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    partial void OnValorChanging(System.Nullable<decimal> value);
    partial void OnValorChanged();
    partial void OnCaminhoImagemChanging(string value);
    partial void OnCaminhoImagemChanged();
    #endregion
		
		public Servico()
		{
			this._Atendimentos = new EntitySet<Atendimento>(new Action<Atendimento>(this.attach_Atendimentos), new Action<Atendimento>(this.detach_Atendimentos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdServico", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdServico
		{
			get
			{
				return this._IdServico;
			}
			set
			{
				if ((this._IdServico != value))
				{
					this.OnIdServicoChanging(value);
					this.SendPropertyChanging();
					this._IdServico = value;
					this.SendPropertyChanged("IdServico");
					this.OnIdServicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(80)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(100)")]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="Money")]
		public System.Nullable<decimal> Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaminhoImagem", DbType="VarChar(1000)")]
		public string CaminhoImagem
		{
			get
			{
				return this._CaminhoImagem;
			}
			set
			{
				if ((this._CaminhoImagem != value))
				{
					this.OnCaminhoImagemChanging(value);
					this.SendPropertyChanging();
					this._CaminhoImagem = value;
					this.SendPropertyChanged("CaminhoImagem");
					this.OnCaminhoImagemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Servico_Atendimento", Storage="_Atendimentos", ThisKey="IdServico", OtherKey="IdServico")]
		public EntitySet<Atendimento> Atendimentos
		{
			get
			{
				return this._Atendimentos;
			}
			set
			{
				this._Atendimentos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Atendimentos(Atendimento entity)
		{
			this.SendPropertyChanging();
			entity.Servico = this;
		}
		
		private void detach_Atendimentos(Atendimento entity)
		{
			this.SendPropertyChanging();
			entity.Servico = null;
		}
	}
}
#pragma warning restore 1591
